version: '3'
services:
  # backend (spring boot)
  springapp:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - healthy
    volumes:
      - ./api:/app  # mounting a volume to hot reload container to source code 
    depends_on:
      - mysqldb
      - redis
  
  # frontend (react)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:5173
    networks:
      - healthy
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules  # prevent local overwrite the container's node_modules
    depends_on:
      - springapp
    
  # mysql
  mysqldb:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 2862003(())aa
      MYSQL_DATABASE: healthy
      MYSQL_USER: kuroko
      MYSQL_PASSWORD: 2862003
    ports:
      - 3307:3307 # host port: container port
    networks:
      - healthy
    volumes:
      - mysqldata:/var/lib/mysql  # persist container data
    restart: always

  # redis
  redis:
    build:
      context: ./cache
      dockerfile: Dockerfile
    ports:
      - 6379:6379
    volumes:
      - ./cache:/data
    networks:
      - healthy

  # rabbitmq
  # rabbitmq:
  #   image: rabbitmq:3.12-alpine
  #   restart: always
  #   volumes:
  #     - ./rabbitmq:/var/lib/rabbitmq
  #   ports:
  #     - "5672:5672"  # RabbitMQ default port
  

networks:
  healthy:  # create common network between spring app and mysqldb
volumes:
  mysqldata:
